### ISSUE TITLE
Unused variables tempToken (and user) | performance & maintainability

### ISSUE THREAD

**Issue by factuminc** [Mshuu/mcafeedex#12]
This is not necessarily an issue; however, depending on if you are experiencing performance challenges then removing these unused variables could help.

----Potentially Expensive-----
variable tempToken assigned but unused:
https://github.com/Mshuu/mcafeedex/blob/a0d099446bc77d84d655428ddfba9344505bd71d/site/balance.js#L274

variable tempToken assigned but unused:
https://github.com/Mshuu/mcafeedex/blob/a0d099446bc77d84d655428ddfba9344505bd71d/site/balance.js#L281

----Likely Not Expensive-----
variable user assigned but unused:
https://github.com/Mshuu/mcafeedex/blob/a0d099446bc77d84d655428ddfba9344505bd71d/site/balance.js#L147

variable user assigned but unused:
https://github.com/Mshuu/mcafeedex/blob/a0d099446bc77d84d655428ddfba9344505bd71d/site/balance.js#L237

I would be most concerned about the two tempToken instances since they reference a functional expression TokenMatches. Depending on how expensive TokenMatches is in terms of performance, these instances could impact performance of balances js anytime updating totals happens to get triggered. I will have to examine the system more to understand how frequently totals update is triggered and how expensive re-executing these computations are. Aside from expensiveness of the TokenMatches computations, this could potentially get optimized depending on your server stack [ js vm / engine]. Worst case of optimization is that these references could 1]create implicitly declared copies of the TokenMatches functional expression and 2]execute potentially expensive operations; however I would be most concerned about number 2] if you feel that you have good optimization with your server-side stack. Really, as I get a better understanding the scope of totals updating and expensiveness of the calculations that could render this a non-issue but I wanted to point this out just in case we are finding ourselves searching for optimizations.

**Comment by Mshuu** [comment]
It's definitely a non issue, the tokenmatches function is quick and inexpensive. I'll keep it open but low priority, someone can go in and remove those eventually.

**Comment by Mshuu** [comment]
Closing this, really doesn't need to be fixed.
