### ISSUE TITLE
Light mode - white text on self orders

### ISSUE THREAD

**Issue by Mshuu** [Mshuu/mcafeedex#38]
When looking at the orderbook your own orders are white, in the light mode that doesn't work at all.

**Comment by Coinsman** [comment]
I had seen the bug previously but now it may had gone.

**Comment by Coinsman** [comment]
https://github.com/Mshuu/mcafeedex/commit/677b59135779ec24629e029cde7e198d9457b2cd

**Comment by Coinsman** [comment]
So sorry if my fix can not help. Just read your message on Telegram.
