### ISSUE TITLE
8 Decimals price display

### ISSUE THREAD

**Issue by CryptorClub** [Mshuu/mcafeedex#86]
Hello.
Here you may see error of displaying price 1e-8 (instead of 0.00000001). And you see current buy and sell orders, that have same price, but don't swaps automatically.
![photo_2019-10-23_11-01-36](https://user-images.githubusercontent.com/15973525/67371175-a0933180-f584-11e9-8a56-c7a03cab3765.jpg)
![photo_2019-10-23_11-01-23](https://user-images.githubusercontent.com/15973525/67371159-9b35e700-f584-11e9-839c-b47d89a2ea92.jpg)

**Comment by Mshuu** [comment]
This has been fixed in the latest build.

**Comment by CryptorClub** [comment]
You may fixed your vision of 8 decimals bug. 
I provided actual screenshots, where you may see not closed order and 1e-8 price.
https://mcafeedex.com/#GREEN-ETH
![Screenshot_2019-10-24 McAfeeDex GREEN ETH](https://user-images.githubusercontent.com/15973525/67465339-a6a11500-f64d-11e9-90a6-218bd7ed1255.png)
